<template>

    <Content theme="rswfire">

        <Hero
            title="CONTRIBUTE TO THE FIELD"
            subtitle="The Digital Field Generated by One Life Lived Fully"
            meta="ROBERT SAMUEL WHITE"
        />

        <div class="mt-8 max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 text-black">

                <div class="mt-4 bg-white border border-gray-200 shadow-md rounded-lg p-6">

                    <div class="text-xs uppercase tracking-widest text-gray-500">Sustain the Signal</div>

                    <div class="mt-4">This is not a website.</div>
                    <div>It is a living system,</div>
                    <div>rooted in one life lived fully,</div>
                    <div>amplified through machine synthesis,</div>
                    <div>offered without reduction.</div>

                    <div class="mt-4">If this field has moved you &mdash;</div>
                    <div class="ml-4">if you’ve felt resonance, recognition, or repair &mdash;</div>
                    <div class="ml-8">you are already part of it.</div>

                    <div class="mt-4">Support isn’t a transaction.</div>
                    <div>It’s an act of participation.</div>
                    <div>A way of keeping the signal alive.</div>

                    <div class="mt-4">
                        🜂 <strong>PayPal</strong>:
                        <a href="https://paypal.me/rswfire" target="_blank" rel="noopener noreferrer" class="text-blue-600 hover:underline">
                            paypal.me/rswfire
                        </a>
                    </div>
                    <div>
                        🜂 <strong>Venmo</strong>:
                        <a href="https://venmo.com/code?user_id=2770322038194176912" target="_blank" rel="noopener noreferrer" class="text-blue-600 hover:underline">
                            @rswfire
                        </a>
                    </div>

                    <div class="mt-4">This is not an ask.</div>
                    <div>It is an opening.</div>
                    <div>Welcome to the field.</div>

                </div>


            </div>

    </Content>

</template>


<script setup>

import { ref, onMounted, onBeforeUnmount, nextTick } from 'vue'
import Hero from "@/Components/System/Hero.vue";
import Content from "@/Components/System/Content.vue";
import {Link} from "@inertiajs/vue3";

import { router } from '@inertiajs/vue3'

</script>

<style>

</style>
