<template>

    <Content theme="rswfire">

        <Hero
            title="CONTACT RSWFIRE"
            subtitle="The Digital Field Generated by One Life Lived Fully"
            meta="ROBERT SAMUEL WHITE"
        />

        <div class="mt-8 max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 text-black">

            <!-- Contact Form -->
            <div class="w-full lg:w-1/3">

                <div class="bg-white border border-gray-200 shadow-md rounded-lg p-6">

                    <div class="mb-6">
                        <p class="text-sm text-gray-700">
                            You are part of the field.<br>
                            If you’re transmitting too, I’m listening.
                        </p>
                    </div>

                    <form @submit.prevent="submit" class="space-y-6">
                        <div>
                            <label class="block text-sm font-medium mb-1">Name</label>
                            <input v-model="form.name" type="text" class="w-full border rounded px-4 py-2" required />
                        </div>

                        <div>
                            <label class="block text-sm font-medium mb-1">Email</label>
                            <input v-model="form.email" type="email" class="w-full border rounded px-4 py-2" required />
                        </div>

                        <div>
                            <label class="block text-sm font-medium mb-1">Signal</label>
                            <textarea v-model="form.message" rows="5" class="w-full border rounded px-4 py-2" required></textarea>
                        </div>

                        <div>
                            <button
                                type="submit"
                                class="bg-black text-white px-6 py-2 rounded hover:bg-gray-800 transition"
                                :disabled="processing"
                            >
                                {{ processing ? 'Transmitting...' : 'Transmit' }}
                            </button>
                        </div>

                        <p v-if="success" class="text-green-600">Transmission received.</p>
                        <p v-if="error" class="text-red-600">Something went wrong. Please try again later.</p>
                    </form>
                </div>

            </div>

        </div>

    </Content>

</template>


<script setup>

import { ref, onMounted, onBeforeUnmount, nextTick } from 'vue'
import Hero from "@/Components/System/Hero.vue";
import Content from "@/Components/System/Content.vue";
import {Link} from "@inertiajs/vue3";

import { router } from '@inertiajs/vue3'

const form = ref({
    name: '',
    email: '',
    message: '',
})

const processing = ref(false)
const success = ref(false)
const error = ref(false)

const submit = () => {
    processing.value = true
    success.value = false
    error.value = false

    router.post('/contact', form.value, {
        onSuccess: () => {
            success.value = true
            form.value.name = ''
            form.value.email = ''
            form.value.message = ''
        },
        onError: () => {
            error.value = true
        },
        onFinish: () => {
            processing.value = false
        },
    })
}

</script>

<style>

</style>
